### PR TITLE
MinioAdminClient: add missing fields to getServerInfo API

### LINKED ISSUE #1602: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException:  Unrecognized field "totalWaiting" (class io.minio.admin.messages.info.DiskMetrics),  not marked as ignorable (4 known properties: "lastMinute", "apiCalls", "totalErrorsAvailability", "totalErrorsTimeout"])
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: 
Unrecognized field "totalWaiting" (class io.minio.admin.messages.info.DiskMetrics), 
not marked as ignorable (4 known properties: "lastMinute", "apiCalls", "totalErrorsAvailability", "totalErrorsTimeout"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1038] 
 (through reference chain: 
 io.minio.admin.messages.info.Message["servers"]->java.util.ArrayList[0]->io.minio.admin.messages.info.ServerProperties["drives"]->
 java.util.ArrayList[0]->io.minio.admin.messages.info.Disk["metrics"]->io.minio.admin.messages.info.DiskMetrics["totalWaiting"])

### PR DESCRIPTION
**Pull request by GTBABC**
Fixes #1602

### CODE REVIEW

File: adminapi/src/main/java/io/minio/admin/messages/info/DiskMetrics.java [hunk 1]
```diff
@@ -40,6 +40,18 @@ public class DiskMetrics {
   @JsonProperty("totalErrorsTimeout")
   private Integer totalErrorsTimeout;
 
+  @JsonProperty("totalTokens")
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/messages/info/DiskMetrics.java:43]: Please add `@JsonIgnoreProperties(ignoreUnknown = true)` to this class

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: adminapi/src/main/java/io/minio/admin/messages/info/DiskMetrics.java (hunk 1 above)
Comment (GTBABC) [reply adminapi/src/main/java/io/minio/admin/messages/info/DiskMetrics.java:45]: ok，I've added

**Review by balamurugana — APPROVED** [review]

**Review by minio-trusted — APPROVED** [review]
