### PR TITLE
fix versionId null check in getPresignedObjectUrl properly

### LINKED ISSUE #1692: Regression: getPresignedObjectUrl adds empty versionId when null
Hello,

I think i have managed to pinpoint a bug in the latest version `9.0.0`. There appears to be a regression in `getPresignedObjectUrl` method in `MinioClient` class. It looks like a simple invalid (inverted) condition in the source code.

Current code `9.0.0`
```java
Http.QueryParameters queryParams = new Http.QueryParameters();
if (args.versionId() == null) queryParams.put("versionId", args.versionId());
```

Previous version `8.6.0`
```java
Multimap<String, String> queryParams = newMultimap(args.extraQueryParams());
if (args.versionId() != null) queryParams.put("versionId", args.versionId());
```

Impact:
- When versionId is null or not set, the SDK generates `versionId=` in query params.
- When versionId is set, the SDK does not add `versionId` to query params.
- This results in malformed presigned URLs.
- Can lead to signature mismatch errors with S3-compatible backends.

Expected behavior:
- versionId should only be added if non-null.

Workaround (applicable only if you do not use `versionId` param):
- Explicitly set versionId to any non-null value.
```java
minioClient.getPresignedObjectUrl(
  GetPresignedObjectUrlArgs.builder()
  .versionId("dummy")
  // other params
  .build()
)
```

This seems like a simple regression with potentially broad impact, but it looks like a fix is fairly simple.

### PR DESCRIPTION
**Pull request by Paw565pl**
Fixes #1692

### CODE REVIEW

**Comment by Paw565pl** [comment]
I have added a small assertion to prevent this regression from happening in the future. If you would like any changes let me know 🙂

File: functional/TestMinioClient.java [hunk 1]
```diff
@@ -1270,6 +1270,20 @@ public void testGetPresignedObjectUrlForGet() throws Exception {
...
+        String urlString =
+            client.getPresignedObjectUrl(
+                GetPresignedObjectUrlArgs.builder()
+                    .method(Http.Method.GET)
+                    .bucket(bucketName)
+                    .object(objectName)
+                    .versionId(versionId)
+                    .build());
+        Assertions.assertTrue(
+            urlString.contains("versionId=" + versionId),
```
Comment (balamurugana) [inline functional/TestMinioClient.java]: Parse the generated url using `okhttp3.HttpUrl.parse()` and validate `versionId` query param for concrete check.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: functional/TestMinioClient.java (hunk 1 above)
Comment (Paw565pl) [reply functional/TestMinioClient.java]: should be ok now

**Review by balamurugana — APPROVED** [review]

**Comment by programista10kpln** [comment]
merge pls
