### PR TITLE
AdminClient: add getDataUsageInfo API

### LINKED ISSUE #1381: Missing DataUsageInfo admin operation
Current MinIO admin API exposes various bucket information, related to data usage (mostly related to estimated size, how many objects are there, etc.) via `/minio/api/v3/datausageinfo` endpoint - https://github.com/minio/minio/blob/RELEASE.2022-11-08T05-27-07Z/cmd/admin-handlers.go#L489 (wrongly named endpoint, correct one is https://github.com/minio/minio/blob/76d822bf1e0c7e47cc1952edb6d3c8b64593863f/cmd/admin-router.go#L68 )

The existence of this operation in `minio-admin` Java library would be very helpful, as currently you're able to manage Quota operations (e.g. fetch current Quota settings), but you don't actually know how big the bucket is.

### PR DESCRIPTION
**Pull request by lukasraska**
This PR implements full support for `DataUsageInfo` object (https://github.com/minio/minio/blob/RELEASE.2022-11-08T05-27-07Z/cmd/data-usage-utils.go ), which can be retrieved via admin API.

Fixes #1381

### CODE REVIEW

File: adminapi/src/main/java/io/minio/admin/DataUsageInfo.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+
+package io.minio.admin;
+
+import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
+import com.fasterxml.jackson.annotation.JsonProperty;
+import java.util.Map;
+
+/** Represents Data usage of the current object APi. */
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class DataUsageInfo {
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/DataUsageInfo.java:26]: Add all missing objects and make it complete than partial support.

**Review by balamurugana — CHANGES_REQUESTED** [review]

File: adminapi/src/main/java/io/minio/admin/DataUsageInfo.java (hunk 1 above)
Comment (lukasraska) [reply adminapi/src/main/java/io/minio/admin/DataUsageInfo.java]: @balamurugana Done. As there are few model classes instead of just those two small ones, I've created new package to hold these. I've also included simple test that the full object can actually be deserialized via Jackson

File: adminapi/src/test/java/io/minio/admin/DataUsageInfoTest.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
+/*
+ * MinIO Java SDK for Amazon S3 Compatible Cloud Storage,
+ * (C) 2021 MinIO, Inc.
```
Comment (balamurugana) [inline adminapi/src/test/java/io/minio/admin/DataUsageInfoTest.java:3]: fix year to 2022

File: adminapi/src/test/resources/json/datausageinfo.json [hunk 3]
```diff
@@ -0,0 +1,43 @@
+{
```
Comment (balamurugana) [inline adminapi/src/test/resources/json/datausageinfo.json:1]: You could embed this as a string in tests.

File: adminapi/src/main/java/io/minio/admin/model/TierStats.java [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+
+/**
+ * Per-tier stats of a remote tier.
+ *
+ * @see https://github.com/minio/minio/blob/master/cmd/data-usage-cache.go#L102
+ */
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class TierStats {
+  @JsonProperty("TotalSize")
+  private long totalSize;
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/model/TierStats.java:31]: You could make this fields as `public` to avoid getters.

File: adminapi/src/main/java/io/minio/admin/model/DataUsageInfo.java [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+
+/**
+ * Represents data usage stats of the current object APi.
+ *
+ * @see https://github.com/minio/minio/blob/master/cmd/data-usage-utils.go#L69
+ */
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class DataUsageInfo {
+  @JsonProperty("lastUpdate")
+  private Date lastUpdate;
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/model/DataUsageInfo.java:33]: You could make this fields as `public` to avoid getters.

File: adminapi/src/main/java/io/minio/admin/model/BucketUsageInfo.java [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+
+/**
+ * Represents bucket usage stats of the current object APi.
+ *
+ * @see https://github.com/minio/minio/blob/master/cmd/data-usage-utils.go#L47
+ */
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class BucketUsageInfo {
+  @JsonProperty("size")
+  private long size;
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/model/BucketUsageInfo.java:32]: You could make this fields as `public` to avoid getters.

File: adminapi/src/main/java/io/minio/admin/model/BucketTargetUsageInfo.java [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+
+/**
+ * Represents bucket replica stats of the current object APi.
+ *
+ * @see https://github.com/minio/minio/blob/master/cmd/data-usage-utils.go#L34
+ */
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class BucketTargetUsageInfo {
+  @JsonProperty("objectsPendingReplicationTotalSize")
+  private long objectsPendingReplicationTotalSize;
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/model/BucketTargetUsageInfo.java:31]: You could make this fields as `public` to avoid getters.

File: adminapi/src/main/java/io/minio/admin/model/AllTierStats.java [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+
+/**
+ * Collection of per-tier stats across all configured remote tiers
+ *
+ * @see https://github.com/minio/minio/blob/master/cmd/data-usage-cache.go#L63
+ */
+@JsonIgnoreProperties(ignoreUnknown = true)
+public class AllTierStats {
+  @JsonProperty("Tiers")
+  private Map<String, TierStats> tiers;
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/model/AllTierStats.java:32]: You could make this fields as `public` to avoid getters.

File: adminapi/src/main/java/io/minio/admin/MinioAdminClient.java [hunk 9]
```diff
@@ -29,6 +29,7 @@
 import io.minio.S3Escaper;
 import io.minio.Signer;
 import io.minio.Time;
+import io.minio.admin.model.DataUsageInfo;
```
Comment (balamurugana) [inline adminapi/src/main/java/io/minio/admin/MinioAdminClient.java:32]: You could have `messages` instead of `model` like `io.minio.messages`

File: adminapi/src/test/resources/json/datausageinfo.json (hunk 3 above)
Comment (lukasraska) [reply adminapi/src/test/resources/json/datausageinfo.json]: I could, but given the string would be pretty large and this project is still supporting Java 8 (text blocks are Java 15+), I would still prefer to have it in resources

File: adminapi/src/main/java/io/minio/admin/model/TierStats.java (hunk 4 above)
Comment (lukasraska) [reply adminapi/src/main/java/io/minio/admin/model/TierStats.java]: I want to avoid this approach as much as I can. Not only it's against all best practices in Java, but it would make the whole minio-java API inconsistent. For example https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/messages/Stats.java doesn't expose any literals directly, only via getters. Same with the other object types - only retrievable via getters and there is no option to actually change them.

I've changed the `getTotalSize()` and all other getters in all messages into the same structure as it's used in the `api` module -> `totalSize()` (so the `get` part is omitted), also I've made all collections returned from those getters unmodifiable, to be consistent with the approach already set here. 

Let me know if it's ok this way or not. Thanks

**Comment by lukasraska** [comment]
One thing that's questionable currently is the usage of `Date` for `DataUsageInfo.lastUpdate` field. While I would want to switch it to newer API (such as `ZonedDateTime` used in `api` module), it would mean introduction of new `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` dependency, so it that's ok, I would include it there as well. Thanks

File: adminapi/src/test/resources/json/datausageinfo.json (hunk 3 above)
Comment (balamurugana) [reply adminapi/src/test/resources/json/datausageinfo.json]: > One thing that's questionable currently is the usage of `Date` for `DataUsageInfo.lastUpdate` field. While I would want to switch it to newer API (such as `ZonedDateTime` used in `api` module), it would mean introduction of new `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` dependency, so it that's ok, I would include it there as well. Thanks

Please go with `ZonedDateTime`

Comment (lukasraska) [reply adminapi/src/test/resources/json/datausageinfo.json]: @balamurugana done

**Review by balamurugana — APPROVED** [review]
